import type { IconType } from 'react-icons';
import {
  SiDocker,
  SiKubernetes,
  SiRust,
  SiReact,
  SiPython,
  SiTypescript,
  SiTailwindcss,
  SiVercel,
  SiGithub,
  SiFirefox,
  SiLinux,
  SiSpotify,
  SiFirebase,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiNetflix,
  SiDuolingo,
  SiSnapchat,
  SiAstro,
  SiPrisma,
  SiBun,
  SiGraphql,
} from 'react-icons/si';

export const ICON_MAP: Record<string, IconType> = {
  SiDocker,
  SiKubernetes,
  SiRust,
  SiReact,
  SiPython,
  SiTypescript,
  SiTailwindcss,
  SiVercel,
  SiGithub,
  SiFirefox,
  SiLinux,
  SiSpotify,
  SiFirebase,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiNetflix,
  SiDuolingo,
  SiSnapchat,
  SiAstro,
  SiPrisma,
  SiBun,
  SiGraphql,
};

// Brand color per icon. Fallback is `currentColor` so the icon picks up the
// surrounding text color when an entry is missing.
export const BRAND_COLORS: Record<string, string> = {
  SiDocker: '#2496ED',
  SiKubernetes: '#326CE5',
  SiRust: '#CE422B',
  SiReact: '#61DAFB',
  SiPython: '#3776AB',
  SiTypescript: '#3178C6',
  SiTailwindcss: '#06B6D4',
  SiFirefox: '#FF7139',
  SiLinux: '#F0C40A',
  SiSpotify: '#1DB954',
  SiFirebase: '#FFCA28',
  SiPostgresql: '#4169E1',
  SiMongodb: '#47A248',
  SiRedis: '#DC382D',
  SiNetflix: '#E50914',
  SiDuolingo: '#58CC02',
  SiSnapchat: '#F4D703',
  SiAstro: '#FF5D01',
  SiPrisma: '#5A67D8',
  SiBun: '#F471B5',
  SiGraphql: '#E10098',
};
